name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  slides:
    name: Generate slides
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Phuse PDF
        run: echo "# npx @marp-team/marp-cli slides/phuse.md -o phuse/slides.pdf --allow-local-files"
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push slides
        uses: EndBug/add-and-commit@v5
        with:
          branch: main
          message: 'Update slides'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
