name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  slides:
    name: Generate slides
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: 6 min slides
        run: npx @marp-team/marp-cli ./slides/slides6min.md -o ./appdev/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: DevOps slides
        run: npx @marp-team/marp-cli ./slides/devops.md -o ./devops/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: MSUG slides
        run: npx @marp-team/marp-cli ./slides/msug.md -o ./msug/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push slides
        uses: EndBug/add-and-commit@v5
        with:
          branch: main
          message: 'Update slides'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
